const apiKey = 'AIzaSyBFkGgQhiDvoFfGjCXETUlNysKGBOEJu8E';
const apiKeyBiteship =
    'biteship_live.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGhyaWZ0bWVlIiwidXNlcklkIjoiNjRkNzA2ZjZmYjc3NjY1NWY1OTQ4MWVjIiwiaWF0IjoxNjkzNDk1OTQzfQ.Iq72AdFO6YlM_srUvlhQx2FTU4TWLMVq5LKpmuoRBfQ';
