name: thriftmee
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  custom_marker: ^1.0.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  geolocator: ^10.0.0
  get: 4.6.5
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.4.0
  http: ^1.1.0
  lottie: ^2.6.0
  permission_handler: ^10.4.3
  persistent_bottom_nav_bar: ^5.0.2
  sentry_flutter: ^7.8.0
dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: 2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
flutter_native_splash:
  color: "#ffffff"
  color_dark_android: "#ffffff"
  color_dark_ios: "#ffffff"
  color_ios: "#ffffff"
  image: assets/img/splash_screen.png
  android: true
  ios: true
  android_12:
    image: assets/img/splash_screen.png
    image_dark: assets/img/splash_screen.png
    color: "#ffffff"
    color_dark: "#ffffff"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/splash_screen.png"
  min_sdk_android: 21
