name: thriftmee
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  get: 4.6.5
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_lints: 2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
flutter_native_splash:
  color: #fff
  image: https://res.cloudinary.com/dkkga3pht/image/upload/v1689308964/Asset_1_1_nveabi.png
  android: true
  ios: true
  android_12:
    image: https://res.cloudinary.com/dkkga3pht/image/upload/v1689308964/Asset_1_1_nveabi.png
    image_dark: https://res.cloudinary.com/dkkga3pht/image/upload/v1689308964/Asset_1_1_nveabi.png
    color : #fff
    color_dark: #fff
