name: thriftmee
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  get: 4.6.5
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: 2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
flutter_native_splash:
  color: "#ffffff"
  color_dark_android: "#ffffff"
  color_dark_ios: "#ffffff"
  color_ios: "#ffffff"
  image: assets/img/splash_screen.png
  android: true
  ios: true
  android_12:
    image: assets/img/splash_screen.png
    image_dark: assets/img/splash_screen.png
    color: "#ffffff"
    color_dark: "#ffffff"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/splash_screen.png"
  min_sdk_android: 21
